#!/bin/bash


POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_USER="${POSTGRES_USER:-pythia}"
POSTGRES_DB="${POSTGRES_DB:-pythia}"

echo 'rebuilding schema'

set -e

./schema

psql -h $POSTGRES_HOST -U $POSTGRES_USER -v "ON_ERROR_STOP=1" $POSTGRES_DB -f ../seeds/seed.sql $@
